### ISSUE TITLE
Permission denied!

### ISSUE THREAD

**Issue by michailVestnik** [hayd/deno-docker#107]
Hi!

1. I write simple test:

```js
import { Application } from 'https://deno.land/x/abc@v1.2.4/mod.ts'

const app = new Application()

const test = 'Test string'
const encoder = new TextEncoder()
const data = encoder.encode(test)

app.get('/', async (c) => {
    await Deno.writeFile('test.txt', data)
    return test
})

app.start({ 
    port: 8080 
})
```

it allows you to understand how the file is being created and written.

2. Dockerfile

```
FROM hayd/alpine-deno:1.7.2
EXPOSE 8080
WORKDIR /app
USER deno
ADD . .
RUN deno cache app.js
CMD ["run", "--allow-net", "--allow-read", "--allow-write", "app.js"]
```

3. Run command in your example: `docker build -t app . && docker run -it --init -p 8080:8080 app`

Without writing files, everything works fine, but if create and write files, I see an error:

![Screenshot_1](https://user-images.githubusercontent.com/75129392/107182707-95d20980-6a20-11eb-839a-4a2601f0555d.png)

I test this example with Alpine Linux & CentOS
I'm doing this for the first time, maybe it's a simple task, but please tell me how to fix it?

**Comment by hayd** [comment]
By default:

```
USER deno
```
won't have access to write files. This is by design.

What you should do is either remove the `USER deno` or set the permissions of `/app` (or another directory) to be writable by the deno user e.g. something like `chown -R deno /app`.

**Comment by michailVestnik** [comment]
thank you very much!
You've helped me a lot!
