### ISSUE TITLE
Should these Dockerfiles build on Docker Hub?

### ISSUE THREAD

**Issue by kuhlaid** [hayd/deno-docker#111]
I tried building the CentoOs docker file (from Feb 5, 2021) on [Docker Hub](https://hub.docker.com/):
https://github.com/hayd/deno-docker/blob/490c69578c4321006a10dc1a33150d945808740e/centos.dockerfile

However it fails at step 7 with the following error:
```
Step 7/10 : COPY ./_entry.sh /usr/local/bin/docker-entrypoint.sh
COPY failed: stat /var/lib/docker/tmp/docker-builder854232540/_entry.sh: no such file or directory
```

**Comment by hayd** [comment]
The entrypoint script _entry.sh is also in this repo, and required.

I'm not sure I understand the question.

**Comment by kuhlaid** [comment]
My apologies @hayd I was not using the _entry.sh, so that is my mistake. Thank you for putting together these Dockerfiles. They are most helpful! - cheers
