### ISSUE TITLE
Creating a Dockerfile with `FROM hayd/deno` does not respond to requests

### ISSUE THREAD

**Issue by alextes** [hayd/deno-docker#46]
With Dockerfile:
```dockerfile
FROM hayd/deno
EXPOSE 8080
WORKDIR /app
ADD . /app
CMD ["run", "--allow-net", "main.ts"]
```

main.ts
```ts
import { serve } from "https://deno.land/std@v0.51.0/http/server.ts";
const s = serve({ port: 8080 });
console.log('listening :8080')
for await (const req of s) {
  req.respond({ body: "Hello World\n" });
}
```

```
$ curl localhost:8080
curl: (52) Empty reply from server
```

Note the `FROM hayd/deno` with `FROM hayd/alpine-deno` it works just fine. That's what it says in the README too, so I'd be totally fine with a 'won't fix', just leaving this here for others that may like me naively use the unversioned image.

**Comment by rianfloo** [comment]
@alextes Di you try to add host to 0.0.0.0 in your main.ts file ?

**Comment by alextes** [comment]
I did not try that. Does docker require the address to be 0.0.0.0? Do other runtimes figure that out and bind that by themselves?

**Comment by hayd** [comment]
That is the problem. It is 0.0.0.0 in the example.

https://github.com/hayd/deno-docker/blob/master/example/main.ts

This should 100% be added in the README as it's a gotcha. (It's something to do with how docker  network namespace e.g. [see SO](https://stackoverflow.com/a/41049825).) I'll keep this open until I add the sample/example code into the README.

I had thought the default was changed in deno to 0.0.0.0 here? https://github.com/denoland/deno/pull/5203

**Comment by hayd** [comment]
@alextes just to confirm, what version of deno is this and what command are you using to start docker? (specifcally are you doing the port forwarding -p 8080:8080 ?)

**Comment by alextes** [comment]
@hayd that change to deno has fixed it. Had a reproduction repo here: https://github.com/alextes/reproduce-bug/tree/master/deno-docker-plain

It works now!

I'd missed the example in this repo and was looking at the one in deno std 👍 .
