### ISSUE TITLE
Don't use deno as entrypoint

### ISSUE THREAD

**Issue by DanielRamosAcosta** [hayd/deno-docker#57]
I think it should be a `docker-entrypoint.sh` file, like [node](https://github.com/nodejs/docker-node/blob/master/14/alpine3.12/docker-entrypoint.sh) does.

This would allow using the image for launching other kind of scripts, and allowing Gitlab CI to work, for example.

I cant PR if you want. Cheers!

**Comment by hayd** [comment]
Thanks for opening an issue / bringing this up!

Could you explain the benefit? What is it solving? How would this change the usage? (How do you call bash in the node image?)

Why doesn't --entrypoint suffice? Why does it break gitlab?

This was suggested and introduced by @Minigugus in #23. Would be interested to hear their counter.

I'm not adverse to this change, but I did think it was neat... But I just want to understand more fully.

**Comment by Minigugus** [comment]
@DanielRamosAcosta Oh nice :open_mouth: Pretty cool to bypass `--entrypoint` easly :laughing: 

@hayd Currently, `docker run -it --rm hayd/deno:alpine-0.35.0 bash` runs `deno bash`. `docker-entrypoint.sh` solve the problem by detecting that `bash` is a command name, so it just run `bash`, but still runs `deno bash.ts` in `docker run -it --rm hayd/deno:alpine-0.35.0 bash.ts` for instance. `--entrypoint` is cool but it doesn't make it easy to pass command lines not using `deno`. Also, some users can be confused not passing the command name (`deno`) in the command line. :wink:

**Comment by hayd** [comment]
@DanielRamosAcosta Happy to take PR!

**Comment by hayd** [comment]
One annoying part of this is that `test` is a unix command so this would be breaking (at the moment running `test` would run `deno test`). I wonder if there is a workaround for that part 🤔

**Comment by Minigugus** [comment]
It's possible to hard-code Deno commands in `docker-entrypoint.sh`... :confused:

**Comment by DanielRamosAcosta** [comment]
Give me some time, I'll try to prepare a PR during this week 😄

**Comment by hayd** [comment]
something like this?
```bash
#!/bin/bash
set -e

# how to test if $1 is in (run, cache, bundle, completions, eval, fmt, lint, repl, test, types) ?
if [ "$1" = 'run' ]; then
    exec gosu deno "$@"
fi

exec "$@"
```
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#entrypoint

**Comment by Minigugus** [comment]
@hayd 
> how to test if $1 is in (run, cache, bundle, completions, eval, fmt, lint, repl, test, types) ?
```sh
#!/bin/bash
set -e

case "$1" in
    run | \
    cache | \
    bundle | \
    completions | \
    eval | \
    fmt | \
    lint | \
    repl | \
    test) \
    exec gosu deno "$@";;
esac

exec "$@"
```
