### ISSUE TITLE
can't access my serivce

### ISSUE THREAD

**Issue by guzhongren** [hayd/deno-docker#65]
## ENV

```shell
❯ docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:41:33 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683**
```

## docker-compose.yaml

[https://github.com/guzhongren/deno-restful-api-with-postgresql-tdd](https://github.com/guzhongren/deno-restful-api-with-postgresql-tdd)

## Question

```shell
❯ docker-compose ps
                     Name                                   Command               State               Ports            
-----------------------------------------------------------------------------------------------------------------------
deno-restful-api-with-postgresql-tdd_db_1        docker-entrypoint.sh postgres    Up      0.0.0.0:5432->5432/tcp       
deno-restful-api-with-postgresql-tdd_pgadmin_1   /entrypoint.sh                   Up      443/tcp, 0.0.0.0:9099->80/tcp
deno-restful-api-with-postgresql-tdd_restful_1   deno run --allow-net --all ...   Up      0.0.0.0:9000->8000/tcp ****
```

when I start my compose, I can access my pgadmin,and postgresq, but I can't access my service written by deno; plz ,help me to find the cause; at the same times, I can request my health API in docker container, `/api/v1/health`

thx

**Comment by hayd** [comment]
Should the command be `run --allow-net ...` (drop the deno prefix).

(This will be fixed with #57 - `deno run` should also work, I have a version of this on machine but have not yet created a PR...)

**Comment by guzhongren** [comment]
Your suggestion doesn't work, I have tried more ways, there's no method to work, wait for your new PR

**Comment by hayd** [comment]
Please let me know if still an issue in 1.2.3

**Comment by guzhongren** [comment]
Hi， I still can't access my service out of the container, but can do that in the container, 

![image](https://user-images.githubusercontent.com/8743692/89961286-cbfe1e80-dc73-11ea-9a8c-a206afbd5147.png)

```dockerfile
FROM hayd/alpine-deno:1.2.3

# The port that your application listens to.
EXPOSE 1993

WORKDIR /app

COPY deps.ts .
RUN deno cache deps.ts
ENV DB_HOST=host.docker.internal

ADD . .

RUN deno cache ./src/index.ts

CMD ["run", "--allow-net", "--allow-env", "./src/index.ts"]
```

**Comment by hayd** [comment]
any thoughts on this @lucacasonato ? I haven't used docker-compose so am a little unsure about this issue.

> Hi， I still can't access my service out of the container, but can do that in the container,

Is it something like a different port needs to be exposed?

**Comment by tststs** [comment]
if using docker-compose you need to add the port to expose

example:

```yaml

---
version: "3.2"
services:
  deno:
    container_name: deno
    build:
      dockerfile: deno.Dockerfile
      context: .
    image: hayd/alpine-deno:1.8.0
    restart: unless-stopped
    ports:
      - "1993:1993"
```
