### ISSUE TITLE
Add ${DENO_DIR}/bin to $PATH

### ISSUE THREAD

**Issue by JonDum** [hayd/deno-docker#68]
When installing utilities to the global using `deno install` they then can't be used in the image directly.

The image needs a 

```
ENV PATH="${DENO_DIR}/bin:${PATH}"
```
somewhere in it.

Also, I noticed that `deno install` doesn't install to DENO_DIR, it instead installs to `/root/.deno/` which might be a separate issue.

**Comment by hayd** [comment]
This seems reasonable (that `deno install` should work). cc @lucacasonato what do you think?

The doc reads:
```
The installation root is determined, in order of precedence:
  - --root option
  - DENO_INSTALL_ROOT environment variable
  - $HOME/.deno
```
Should DENO_INSTALL_ROOT be set to /usr/local/ or /opt/ ? 🤔  (That seems cleaner that modifying PATH.)
