### ISSUE TITLE
I am getting an error while building a image

### ISSUE THREAD

**Issue by harshadaju** [hayd/deno-docker#81]
When i am trying to run command like
docker build -t app .
![image](https://user-images.githubusercontent.com/20344059/95336578-77230100-08ce-11eb-9496-38b83675639a.png)

Please help me to resolve this

**Comment by ebebbington** [comment]
@harshadaju is your dockerfile named `Dockerfile` or `dockerfile`?

**Comment by hayd** [comment]
closing from lack of reply, please comment if it's still an issue
