### ISSUE TITLE
Is the dockerhub readme missing the "run" command?

### ISSUE THREAD

**Issue by pablit07** [hayd/deno-docker#84]
Hi, I just tried to copy and run the example shown on https://hub.docker.com/r/hayd/alpine-deno/ but noticed it was different than the example shown on github readme.

Github:
`docker run -it --init -p 1993:1993 -v $PWD:/app hayd/alpine-deno:1.0.0 run --allow-net /app/main.ts`
Dockerhub (missing "run"):
`docker run -it --init -p 1993:1993 -v $PWD:/app hayd/alpine-deno:1.0.0 --allow-net /app/main.ts`

I don't think its intentional because the container fails to start with an error

Would you please note to fix? Thanks!

**Comment by hayd** [comment]
Thank you for pointing this out! I think I've pushed a fix across the docker hub READMEs.
