### ISSUE TITLE
'De-bloating' The Dockerfile

### ISSUE THREAD

**Issue by ebebbington** [hayd/deno-docker#86]
Hey @hayd, i personally feel the dockerfile logic could be simplified, here is what I use for any deno container:

```dockerfile
FROM debian:stable-slim

RUN apt update -y \
  && apt clean \
  && apt install bash curl unzip -y

RUN curl -fsSL https://deno.land/x/install/install.sh | DENO_INSTALL=/usr/local sh -s v1.5.1
RUN export DENO_INSTALL="/usr/bin"
RUN export PATH="$DENO_INSTALL/bin:$PATH"
```

I also wonder if it's worth adding `ARGS` support for a deno version? eg:

```
// your dockerfile
ARG DENO_VERSION

Run install deno | v${DENO_VERSION}

// my docker-compose.yml file
deno:
  args: 
    - DENO_VERSION: 1.4.5 # or whatever the syntax is i can't remember fully
```

**Comment by ebebbington** [comment]
closing as duplicate of #79

**Comment by hayd** [comment]
Are we talking about de-bloating the image size or the number of lines in the dockerfile?

**Comment by ebebbington** [comment]
I’m taking about the number of lines in the Docker file, but the image size would be smaller should Debian slim be used - of course any slim image would do but maybe you have reasons to go with the image you’ve chosen

**Comment by hayd** [comment]
Happy to use the slim version, if not already!

I am unsure about using number of lines as a metric, and i am nervous about relying on deno install (compared to only github download, which is also a dependency of deno install) - and deno install is where the lines are :) .

**Comment by ebebbington** [comment]
Fair enough :) I guess what I’m saying in a nutshell is, the installation could be anything, but I feel the content of the dockerfile could be simplified and achieve the same result, without sacrificing readability

**Comment by ebebbington** [comment]
Also someone mentioned they couldn’t get any logs with your dockerfile, but I can’t find the link :/

**Comment by ebebbington** [comment]
Don't suppose we could move this discussion to https://github.com/hayd/deno-docker/issues/79?
