### ISSUE TITLE
Consider adding /usr/bin/env -S support

### ISSUE THREAD

**Issue by yw662** [hayd/deno-docker#97]
Was on hayd/deno where /usr/bin/env is implemented by BusyBox v1.31.1, and `-S` option is not implemented.
However passing parameters to deno is a must, and `env -S` is one of the common methods.

Is there already a deno image supporting `env -S`, or, could it be added somehow ?

**Comment by hayd** [comment]
Could you explain the usecase/give example for `env -S`?

(You could also use the ubuntu/slim images, perhaps they have this.)

**Comment by yw662** [comment]
Exp. in shebang:
#! /usr/bin/env -S deno run --allow-xxx

I know I can do it like `deno run --allow-xxx yyy.ts`, but the parameters appears twice in both Dockerfile/compose.yml and the script.

**Comment by hayd** [comment]
Solution is to not use alpine e.g. hayd/debian-deno or hayd/ubuntu-deno and override the ENTRYPOINT (to the ts file).
Note you need to ensure the file is executable.

I am not sure whether this can even be supported for alpine so am going to close.
